#!/usr/bin/env bash

function __update_full_run() {
  section "update dotfiles"
  echo 'Updating dotfiles…'
  ~//dotfiles/install.sh

  section "update hosts"
  echo 'Updating hosts…'
  if [[ -f ~//hosts ]]; then
    sudo install -m 0644 ~//hosts /etc/hosts
  else
    sudo install -m 0644 ~//hosts.example /etc/hosts
  fi

  section "update apps"
  echo 'Updating App Store apps…'
  mas upgrade
  echo 'Updating Homebrew packages…'
  brew update
  brew upgrade
  brew missing || true
  brew cleanup
  (cd ~//apps/ && brew bundle dump --force --describe)

  builtin cd ~
  clean
  section "update macos"
  softwareupdate -i -a

  # Back up Sublime Text settings
  cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Package\ Control.sublime-settings ~//resources/ 2>/dev/null || true
  cp ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings ~//resources/ 2>/dev/null || true
  section "update settings"
  echo 'Updating Settings…'
  ~//settings
}

function __update_all_run() {
  sfx loop --done=item_acquisition save_station __update_full_run
}

function update() {
  case "$1" in

    # `update apps`
    "apps")
      section "update apps"
      echo 'Updating App Store apps…'
      mas upgrade
      echo 'Updating Homebrew packages…'
      brew update
      brew upgrade
      brew missing || true
      brew cleanup
      (cd ~//apps/ && brew bundle dump --force --describe)
    ;;

    # `update dock`
    "dock") 
      section "update dock"
      echo 'Updating Dock…'
      ~//dock
    ;;

    # `update dotfiles`
    "dotfiles") 
      section "update dotfiles"
      echo 'Updating dotfiles…'
      ~//dotfiles/install.sh
    ;;

    # `update hosts`
    "hosts") 
      section "update hosts"
      echo 'Updating hosts…'
      if [[ -f ~//hosts ]]; then
        sudo install -m 0644 ~//hosts /etc/hosts
      else
        sudo install -m 0644 ~//hosts.example /etc/hosts
      fi
    ;;

      # `update settings`
    "settings")
      section "update settings"
      echo 'Updating Settings…'
      ~//settings
    ;;

    # `update` | Run all of the updates
    "")
      section "update"
      echo 'Requesting root access…'
      root
      __update_all_run
    ;;

  esac
}

complete -W "all apps dock dotfiles hosts settings" update
